config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'perfil', to: 'user#show', as: :user_show
  #get 'user/edit'

  #get 'home/index'
  
  
  
   
  root to: "home#index"  #root_path 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :documento, :fecha_nacimiento, :de_riesgo])
            devise_parameter_sanitizer.permit(:account_update, keys: [:nombre, :documento, :fecha_nacimiento, :de_riesgo])
            #devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name, :dni, :birth_date, :not_covid])
            devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
        end

end

app/controllers/dev/confirmations_controller.rb
# frozen_string_literal: true

class Dev::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/dev/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Dev::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/dev/passwords_controller.rb
# frozen_string_literal: true

class Dev::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/dev/registrations_controller.rb
# frozen_string_literal: true

class Dev::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up

   def new
     super
     @user = User.find(params[:id])
   end

  # POST /resource
   def create
     super
     @user = User.new(params.require(:user).permit(:email, :documento, :de_riesgo, :fecha_nacimiento))

     if @user.save
       redirect_to new_user_session_path, notice: "Se ha registrado exitosamente!"
     else
       flash[:error] = "Hubo un error al intentar registrarse"
       render :new
     end
   end

  # GET /resource/edit
   def edit
     super}
     @u = User.find(params[:id])
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
   def cancel
     super
   end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
   end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     super(resource)
   end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     super(resource)
   end
end

app/controllers/dev/sessions_controller.rb
# frozen_string_literal: true

class Dev::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/dev/unlocks_controller.rb
# frozen_string_literal: true

class Dev::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #listar datos de las instancias

  end
  
  def show
    #mostrar datos de una instancia
  
  end

  def new
    #mostrar formulario de carga(llama a ceate)
    
  end

  def edit
    #mostrar formulario de edicion(llama a update)
    
  end

  def create
    #crea en la BD
  end

  def update
    #modificar datos en la BD
    
  end

  def destroy
    #elimina en la BD
    
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  #GET
  def index
    #listar datos de las instancias

  end
  
  #GET
  def show
    #mostrar datos de una instancia
 
  end

  #GET
  def new
    #mostrar formulario de carga(llama a ceate)
    
  end

  #GET
  def edit
    #mostrar formulario de edicion(llama a update)
    
  end

  #POST
  def create
    #crea en la BD
  end

  #PUT
  def update
    #modificar datos en la BD
    
  end

  #DELETE
  def destroy
    #elimina en la BD
    @user = User.find(params{:documento})
    if @user.id = 1                         #si es Admin
      User.delete(@user.id)
      @mensaje = "Usuario eliminado"
    else
      @mensaje = "Usted no posee los permisos para realizar esta acción"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<!doctype html>
<html> 
<div class="jumbotron center"  >

  		
     		
     		<% if ! signed_in? %>
    			 
    		<h1>BIENVENIDO A VACUNASSIST</h1>

      		<p> <%= link_to "REGISTRARSE", new_user_registration_path , class: 'btn btn-default btn-lg' %>

     		<p> <%= link_to "INICIAR SESION", new_user_session_path , class: 'btn btn-default btn-lg' %> </p> 
     		
  		<% end %>
  		
  		 <% if signed_in?  %>
  		 
  		 <h1> BIENVENIDO A VACUNASSIST</h1> 
  		  
  		  <% if current_user != nil && !current_user.de_riesgo  %> 
  		  	
  		
  			 <p> <%= link_to "SOLICITAR VACUNA PARA LA FIEBRE AMARILLA", '#' , class: 'btn btn-default btn-lg' %> </p>
  			 
		  <% end %>
		  
	 	 <% end %>

</div>
</html> 

app/views/layouts/_header.html.erb
<!doctype html> 
<html>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to 'VACUNASSIST', root_path, class: 'navbar-brand' %> 
      
    </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "INICIO", root_path %></li>
	<li> <%= link_to "NOSOTROS", '#' %></li>
	
	<% if signed_in? %>
    		<li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li> 
    		<li> <%= link_to "PERFIL", user_show_path  %> </li> 
  	<% end %>
  	
          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    
   
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VacunAssist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %> 
      
  

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class = "jumbotron center" >  
  	<%= yield %> 
    </div> 


</html> 
    
    
  </body>
</html>

app/views/layouts/perfil.html.erb
<h1> perfil </h1> 

app/views/user/edit.html.erb
<% if @user != :null %>
  
<% end %>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>


<% if @user != :null%>
    <h1> <%= @user.nombre %><h1>
    <li>
        <p> email: <%= @user.email %> </p>
        <p> DNI: <%= @user.documento %> </p>
        <% if @user.de_riesgo %>
            <p> Paciente de riesgo </p>  
        <% else %>
            <p> No es paciente de riesgo </p>
        <% end %>
        <%= link_to("Editar Perfil", usuer_edit_path) %>
        <%= link_to("Inicio", root_path) %>
    </li>
<% else %>
    <%= flash[:error] = "El usuario no existe"%>
    <% render :home%>
<% end %> 

app/views/user/show.html.erb
<% if current_user != nil %>
    <h1> <%= current_user.nombre %><h1>
    <li>
        <p> email: <%= current_user.email %> </p>
        <p> DNI: <%= current_user.documento %> </p>
        <% if current_user.de_riesgo %>
            <p> Paciente de riesgo </p>  
        <% else %>
            <p> No es paciente de riesgo </p>
        <% end %>
        <%= link_to("Editar Perfil", edit_user_registration_path) %>
        <%= link_to("Inicio", root_path) %>
    </li>
<% else %>
    <%= flash[:error] = "El usuario no existe"%>
    <% render :home%>
<% end %> 